name: root_dependencies
description: Root dependencies provides dependency handler on start up the app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  easy_localization: ^3.0.3
  easy_localization_loader: ^1.0.1+1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.3
  dart_code_metrics_presets: ^2.4.0